for(int i=0;i<n;i++)
    // {
    //     if(mp.find(a[i])!=mp.end())
    //     {
    //         a.erase(a.begin()+i);
    //     }
    //     else
    //     {
    //         continue;
    //     }
    // }